import React from 'react';
import dynamic from 'next/dynamic'
import Head from 'next/head'

const theme = 'lightTheme'

const Index = () => {
  const MainTheme = dynamic(() => import(`../themes/${theme}`))


  return (
    <>
      <Head>
        <title>Role Challenge Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/icon/favicon.ico" />
      </Head>
      <MainTheme/>
    </>
  );
}

export default Index;

